index:
    path: /
    methods: GET
    controller: App\Controller\CommandController::index

tip:
    path: /add/tip
    controller: App\Controller\CommandController::addTip
    methods: POST

add:
    path: /add/cmdline
    controller: App\Controller\CommandController::addLine
    methods: POST

text:
    path: /add/text
    controller: App\Controller\CommandController::addText
    methods: POST

ls:
    path: /add/ls
    controller: App\Controller\CommandController::pizzaList
    methods: POST

uls:
    path: /add/uls
    controller: App\Controller\CommandController::userList
    methods: POST

ols:
    path: /add/ols
    controller: App\Controller\CommandController::orderList
    methods: POST

cart:
    path: /add/cart
    controller: App\Controller\CommandController::userCart
    methods: POST

help:
    path: /add/help
    controller: App\Controller\CommandController::addHelp
    methods: POST

add_complete:
    path: /add/add_complete
    controller: App\Controller\CommandController::addPizzaComplete
    methods: POST

input_line:
    path: /add/input_line
    controller: App\Controller\CommandController::addInputLine
    methods: POST

error:
    path: /add/error
    controller: App\Controller\CommandController::addError
    methods: POST

pizza_list:
    path: /pizza/list
    controller: App\Controller\PizzaController::listPizzas
    methods: POST

pizza_new:
    path: /pizza/new
    controller: App\Controller\PizzaController::createPizza
    methods: POST

pizza_delete:
    path: /pizza/delete/{id}
    controller: App\Controller\PizzaController::deletePizza
    methods: POST

user_check:
    path: user/check_name
    controller: App\Controller\UserController::checkUserName
    methods: POST

user_list:
    path: user/list
    controller: App\Controller\UserController::listUsers
    methods: POST

user_delete:
    path: user/delete/{id}
    controller: App\Controller\UserController::deleteUser
    methods: POST

user_new:
    path: user/new
    controller: App\Controller\UserController::createUser
    methods: POST

get_id:
    path: /security/get_id
    controller: App\Controller\SecurityController::getId
    methods: POST

is_login:
    path: /security/is_login
    controller: App\Controller\SecurityController::isLogin
    methods: POST

is_admin:
    path: /security/is_admin
    controller: App\Controller\SecurityController::isAdmin
    methods: POST

login:
    path: /security/login
    controller: App\Controller\SecurityController::login
    methods: POST

logout:
    path: /security/logout
    controller: App\Controller\SecurityController::logout
    methods: POST

order_create:
    path: /order/create
    controller: App\Controller\OrderController::createOrder
    methods: POST

order_delete:
    path: order/delete/{id}
    controller: App\Controller\OrderController::deleteOrder
    methods: POST

# add_user:
#     path: /user/add_user
#     methods: POST
#     controller: App\Controller\UserController::saveUserToDatabase
    
# show_user:
#     path: /user/show/{id}
#     controller: App\Controller\UserController::showUser
#     methods: GET


# update_user:
#     path: /user/update
#     controller: App\Controller\UserController::updateUserData
#     methods: POST

# delete_user:
#     path: /user/delete
#     controller: App\Controller\UserController::deleteUserFromDatabase
#     methods: POST

# home:
#     path: /user/list
#     controller: App\Controller\UserController::showUsersList
#     methods: GET